<a href="https://colab.research.google.com/github/tanmayc07/ml-essentials/blob/main/pandas_101.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
# Defining array manually
# Creating a 2x2 matrix

np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [4]:
# Numpy has functions to generate arrays without
# entering elements manually

np.arange(1, 5)     # [1,5)

array([1, 2, 3, 4])

In [53]:
np.arange(0, 10, 2) # third param is step

array([0, 2, 4, 6, 8])

In [52]:
# linspace is used instead of arange for floats
np.linspace(0.1, 2.0, 5) # third param is number of elems

array([0.1  , 0.575, 1.05 , 1.525, 2.   ])

In [8]:
# Creating arrays with initalized values

print( np.zeros((3, 1)) )    # shape in () as arg

print( np.ones((3, 1)) )

print( np.full((2, 3), 7) )    # repeat 7

[[0.]
 [0.]
 [0.]]
[[1.]
 [1.]
 [1.]]
[[7 7 7]
 [7 7 7]]


In [21]:
# shape
vector = np.arange(5)
print(f'vector shape: {vector.shape}')

matrix = np.ones([3, 2])
print(f'matrix shape: {matrix.shape}')

tensor = np.full([2, 4, 5], 10)
print(f'tensor shape: {tensor.shape}')  # Tensor is like a set of matrices so first 2 in shape denotes number of matrices/slices

vector shape: (5,)
matrix shape: (3, 2)
tensor shape: (2, 4, 5)


In [20]:
tensor

array([[[10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10]],

       [[10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10]]])

In [54]:
# Array with random values generation using new interface
rng = np.random.default_rng()
rng.integers(0, 10, 3)

array([9, 2, 7])

In [57]:
print(rng.random(10))
print(rng.uniform(1, 10, 3))
'''
others:
rng.standard_normal(3)
rng.normal(5, 2, 3)
'''

[0.6015621  0.52280571 0.65674964 0.50917834 0.891459   0.10477051
 0.4681809  0.40524662 0.21257832 0.11622888]
[7.53930375 8.05139299 8.54745162]


'\nothers:\nrng.standard_normal(3)\nrng.normal(5, 2, 3)\n'

In [25]:
# Reshaping the arrays
arr = np.arange(1, 10)
print(arr)

arr = arr.reshape(3, 3)  # Number of elements should remain same, (3,4) will give error
print(arr)

arr = arr.reshape(9)    # back to original size
print(arr)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


In [31]:
arr = np.arange(0, 12).reshape(2, -1)   # -1 to infer the correct no of digits
print(arr)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [69]:
# Transpose of an array
arr = np.arange(6).reshape((2,3))
print(arr)
print(arr.T) # also arr.transpose()

[[0 1 2]
 [3 4 5]]
[[0 3]
 [1 4]
 [2 5]]


In [33]:
# dtype provides type information
arr.dtype.type

numpy.int64

In [37]:
# Indexing

arr = np.arange(1, 17).reshape(4, -1)
print(arr)
print(f'arr[1, 2:4]:{arr[1,2:4]}')
print(f'arr[1:3, 1:3]: {arr[1:3, 1:3]}')
print(arr[:, 1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
arr[1, 2:4]:[7 8]
arr[1:3, 1:3]: [[ 6  7]
 [10 11]]
[ 2  6 10 14]


In [39]:
arr[1::2, ::2]  # 1: means every row after 1 and :2 means step of 2, ::2 means every column but step of 2

array([[ 5,  7],
       [13, 15]])

In [40]:
# Explicitly specifying columns
arr[1:3, [2,3]]

array([[ 7,  8],
       [11, 12]])

In [43]:
# Concatenating

a1 = arr[:2, :] # First 2 rows
a1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [42]:
a2 = arr[-1:, :]    # Last 1 row
a2

array([[13, 14, 15, 16]])

In [45]:
new_arr = np.vstack((a1, a2))   # vstack concatenates row one after another
new_arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [13, 14, 15, 16]])

In [46]:
# np.hstack will concatenate columns and np.concatenate((start, end), axis=_ ) will concatenate higher dimensional arrays along axis specified

In [47]:
# Splitting the arrays
'''
hsplit: splits along the horizontal axis
vsplit: splits along the vertical axis
dsplit: Splits an array along the 3rd axis (depth)
array_split: lets you specify the axis to use in splitting
'''

'\nhsplit: splits along the horizontal axis\nvsplit: splits along the vertical axis\ndsplit: Splits an array along the 3rd axis (depth)\narray_split: lets you specify the axis to use in splitting\n'

In [58]:
# Vector operations
np.array([2, 3])**2

array([4, 9])

In [61]:
print(np.sqrt( np.array( [4, 9] ) ))
print(np.exp( np.array( [1, 2] ) ))
print(np.log( np.array( [np.e, np.e**2] ) ))

[2. 3.]
[2.71828183 7.3890561 ]
[1. 2.]


In [66]:
# Dot and Cross Products
# a.b
a = np.array([1, 2])
b = np.array([3, 4])

dot1 = np.dot(a, b)
dot2 = a @ b

print(f'{dot1} {dot2}')

# axb
print(f'axb = {np.cross( np.array([2,0,0]), np.array([0,3,0]) )}')

11 11
axb = [0 0 6]
